## Latihan (Practice)
Kerjakan latihan singkat ini di environment Python Anda:

1. Buat NumPy array 1D berisi angka dari 1 sampai 10, lalu kalikan seluruh elemen dengan 2 tanpa menggunakan perulangan (for).

2. Buat Pandas DataFrame yang berisi kolom Produk, Harga, dan Terjual (minimal 4 baris data acak, masukkan 1 nilai NaN di salah satu sel Harga). Tulis kode untuk mendeteksi baris mana yang memiliki nilai NaN tersebut.

### Import Library

In [1]:
import numpy as np
import pandas as pd

Buat NumPy array 1D berisi angka dari 1 sampai 10, lalu kalikan seluruh elemen dengan 2 **tanpa menggunakan perulangan (```for```).**

In [2]:
array_one_dimension = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
"""
Manipulasi data array 1D(1 dimensi) dengan mengalikan masing-masing data dengan 2.
Perbedaan yang saya rasakan saat melakukan manipulasi array 1D adalah kita tidak membutuhkan 
for loop yang banyak untuk mengakses masih-masing data apalagi 
ketika data array nya polanya menjadi 2D(matrix).
"""
manipulation_each_elemen = array_one_dimension * 2
manipulation_each_elemen

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Buat Pandas DataFrame yang berisi kolom Produk, Harga, dan Terjual (minimal 4 baris data acak, masukkan 1 nilai NaN di salah satu sel Harga). Tulis kode untuk mendeteksi baris mana yang memiliki nilai NaN tersebut.

In [51]:
df = pd.DataFrame({
          "Produk": np.array(["Croc", "Nevada", "Adidas", "Under Armour"]), 
          "Harga": np.array([500_000, 150_000, 1_500_000, np.nan]), 
          "Terjual": np.array([50, 90, 40, 35])
          })

In [59]:
df_new = df.copy()
df_new

         Produk      Harga  Terjual
0          Croc   500000.0       50
1        Nevada   150000.0       90
2        Adidas  1500000.0       40
3  Under Armour        NaN       35

In [62]:
df_clean = df_new.dropna().reset_index(drop=True)
df_clean

   Produk      Harga  Terjual
0    Croc   500000.0       50
1  Nevada   150000.0       90
2  Adidas  1500000.0       40

In [63]:
df_clean.isna().sum()

Produk     0
Harga      0
Terjual    0
dtype: int64